param-0 =    "***"
param-1= "{$ENV1}"

# Comment
  # Comment


param-2 = {$ENV2}

{#include ^test_include.toml}


duration1 = "100ns"
duration2 = "5d"
duration3 = "10us"
duration4 = "10u"


param-last = { \
  "x" = 1,     \
  "y" = "Y",   \
}

[http]
listener = { bind-addr = ":1234", ssl-combined-pem = "", timeout = "6s", \
	root = "", \
	proxy-prefix = "/config-test/", \
	icon-file = "/tmp/favicon.ico", \
	disabled-endpoints = [ "/aaa*", "!/aaa/bbb" ], \
	auth = { \
		endpoints = {"/xxx/" = [" *       "], "/yyy" = [" user1 ", " user2", " @group1  "," ! @group2  ", " !user3", "!", " ! "] }, \
		users = {{#include ^users.toml}}, \
		methods = { \
			basic = { enabled = true, options = {} }, \
			jwt   = { enabled = true, options = { secret = "secret-secret", lifetime = 157680000 }, score = 20 }, \
		} \
	} \
}
